SELECT F.NAME,
	F.HP,
	F.ATTACK + W.ATTACKPOWER AS TOTALATTACK,
	F.DEFENSE + W.DEFENSE AS TOTALDEFENSE
FROM FRIEND F
JOIN FRIENDEQUIP FE ON FE.FRIENDID = F.ID
JOIN WEAPON W ON W.ID = FE.WEAPONID
ORDER BY TOTALATTACK DESC