global:
  scrape_interval: 15s
scrape_configs:
  - job_name: node
    static_configs:
      - targets: 
        - monitoring-node-exporter-1:9100
        - monitoring-node-exporter-2:9100
        - monitoring-node-exporter-3:9100